### ISSUE TITLE
Segments3DView TimePointChangedListener

### ISSUE THREAD

**Issue by tischi** [tischi/imagej-utils#37]
@K-Meech @constantinpape

We have to decide what we want to happen to the segments that are shown in the 3D Viewer when the timepoint is changed in BDV. I would think maybe  only show the segments that are visible within the current time point. What do you think?

We have to see how to best communicate this to the `Segments3dView`.
One can register a `TimePointChangedListener` to BDV, we should somehow use this, but ideally in a way that the `Segments3dView` does not know that a BDV exists (for the sake of separation of concerns on the code level).

**Comment by constantinpape** [comment]
If I understand you correctly, we are discussing the following scenario:
- We are in timepoint `t` and segment ids `1, 2, 3` are shown in the 3d viewer.
- Then, we switch to timepoint `t + 1`.
- Which segments should now be selected and shown in the 3d viewer.

I am not sure if we should show anything selected in the previous timestep in the next one, because the ids might not have any meaningful relation between the timesteps.
For example in the dataset I uploaded, they are not directly connected to each other; only the `track_id` (which is in the table) is constant across timesteps.

**Comment by tischi** [comment]
> I am not sure if we should show anything selected in the previous timestep in the next one, because the ids might not have any meaningful relation between the timesteps.

Yes, I agree. I will implement it for now such that it only shows the selected segments of the timepoint that is currently shown in BDV.

If one is interested in exploring the tracking, one can sort the table by  trackID and then select all segments of one trackID in the table and then with the arrow keys move in the table. This should create a nice "movie" of the tracked segment in the 3D viewer.
